### PR TITLE
Rebuild for `nodejs=18`

### PR DESCRIPTION
**Pull request by dhirschfeld**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dhirschfeld** [comment]
```
❯ micromamba repoquery whoneeds nodejs

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

Loaded current active prefix: "/opt/mambaforge/envs/quantdev"

 Name                    Version Build           Depends                 Channel        
─────────────────────────────────────────────────────────────────────────────────────────
 configurable-http-proxy 4.5.4   h7e777a6_0      nodejs >=17.9.0,<18.0a0 conda-forge    
 jupyterhub              3.1.1   pyh2a2186d_0    nodejs >=12             conda-forge    
 ```

**Comment by dhirschfeld** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
Well, that didn't work :thinking:

**Comment by dhirschfeld** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
`nodejs` 18 is the current LTS release so it would be good to support it as some other deps are starting to require it.
* https://nodejs.dev/en/about/releases/

I also opened an issue to remove support for version 17 - #53

**Comment by dhirschfeld** [comment]
It looks like that worked! :tada:

image


ping @conda-forge/configurable-http-proxy

**Comment by minrk** [comment]
Thanks!

**Comment by dhirschfeld** [comment]
> Thanks!

Thank you! 😄

**Pull request merged**
